#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarParkingManagementProject
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Thienhoang")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertdulieuNV(dulieuNV instance);
    partial void UpdatedulieuNV(dulieuNV instance);
    partial void DeletedulieuNV(dulieuNV instance);
    partial void InsertdataKH(dataKH instance);
    partial void UpdatedataKH(dataKH instance);
    partial void DeletedataKH(dataKH instance);
    partial void InsertCarSpaceData(CarSpaceData instance);
    partial void UpdateCarSpaceData(CarSpaceData instance);
    partial void DeleteCarSpaceData(CarSpaceData instance);
    partial void InsertdulieuMotoSpace(dulieuMotoSpace instance);
    partial void UpdatedulieuMotoSpace(dulieuMotoSpace instance);
    partial void DeletedulieuMotoSpace(dulieuMotoSpace instance);
    partial void InsertfeedbackData(feedbackData instance);
    partial void UpdatefeedbackData(feedbackData instance);
    partial void DeletefeedbackData(feedbackData instance);
    partial void InsertdataHistory(dataHistory instance);
    partial void UpdatedataHistory(dataHistory instance);
    partial void DeletedataHistory(dataHistory instance);
    partial void InsertdataHisKH(dataHisKH instance);
    partial void UpdatedataHisKH(dataHisKH instance);
    partial void DeletedataHisKH(dataHisKH instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::CarParkingManagementProject.Properties.Settings.Default.ThienhoangConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<dulieuNV> dulieuNVs
		{
			get
			{
				return this.GetTable<dulieuNV>();
			}
		}
		
		public System.Data.Linq.Table<dataKH> dataKHs
		{
			get
			{
				return this.GetTable<dataKH>();
			}
		}
		
		public System.Data.Linq.Table<CarSpaceData> CarSpaceDatas
		{
			get
			{
				return this.GetTable<CarSpaceData>();
			}
		}
		
		public System.Data.Linq.Table<dulieuMotoSpace> dulieuMotoSpaces
		{
			get
			{
				return this.GetTable<dulieuMotoSpace>();
			}
		}
		
		public System.Data.Linq.Table<feedbackData> feedbackDatas
		{
			get
			{
				return this.GetTable<feedbackData>();
			}
		}
		
		public System.Data.Linq.Table<dataHistory> dataHistories
		{
			get
			{
				return this.GetTable<dataHistory>();
			}
		}
		
		public System.Data.Linq.Table<dataHisKH> dataHisKHs
		{
			get
			{
				return this.GetTable<dataHisKH>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.dulieuNV")]
	public partial class dulieuNV : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _idNV;
		
		private string _nameNV;
		
		private string _genderNV;
		
		private string _phoneNV;
		
		private System.DateTime _birthdayNV;
		
		private System.DateTime _hiredayNV;
		
		private string _addressNV;
		
		private decimal _salaryNV;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidNVChanging(string value);
    partial void OnidNVChanged();
    partial void OnnameNVChanging(string value);
    partial void OnnameNVChanged();
    partial void OngenderNVChanging(string value);
    partial void OngenderNVChanged();
    partial void OnphoneNVChanging(string value);
    partial void OnphoneNVChanged();
    partial void OnbirthdayNVChanging(System.DateTime value);
    partial void OnbirthdayNVChanged();
    partial void OnhiredayNVChanging(System.DateTime value);
    partial void OnhiredayNVChanged();
    partial void OnaddressNVChanging(string value);
    partial void OnaddressNVChanged();
    partial void OnsalaryNVChanging(decimal value);
    partial void OnsalaryNVChanged();
    #endregion
		
		public dulieuNV()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idNV", DbType="NChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string idNV
		{
			get
			{
				return this._idNV;
			}
			set
			{
				if ((this._idNV != value))
				{
					this.OnidNVChanging(value);
					this.SendPropertyChanging();
					this._idNV = value;
					this.SendPropertyChanged("idNV");
					this.OnidNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nameNV", DbType="NChar(50) NOT NULL", CanBeNull=false)]
		public string nameNV
		{
			get
			{
				return this._nameNV;
			}
			set
			{
				if ((this._nameNV != value))
				{
					this.OnnameNVChanging(value);
					this.SendPropertyChanging();
					this._nameNV = value;
					this.SendPropertyChanged("nameNV");
					this.OnnameNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_genderNV", DbType="NChar(50) NOT NULL", CanBeNull=false)]
		public string genderNV
		{
			get
			{
				return this._genderNV;
			}
			set
			{
				if ((this._genderNV != value))
				{
					this.OngenderNVChanging(value);
					this.SendPropertyChanging();
					this._genderNV = value;
					this.SendPropertyChanged("genderNV");
					this.OngenderNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phoneNV", DbType="NChar(50) NOT NULL", CanBeNull=false)]
		public string phoneNV
		{
			get
			{
				return this._phoneNV;
			}
			set
			{
				if ((this._phoneNV != value))
				{
					this.OnphoneNVChanging(value);
					this.SendPropertyChanging();
					this._phoneNV = value;
					this.SendPropertyChanged("phoneNV");
					this.OnphoneNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_birthdayNV", DbType="Date NOT NULL")]
		public System.DateTime birthdayNV
		{
			get
			{
				return this._birthdayNV;
			}
			set
			{
				if ((this._birthdayNV != value))
				{
					this.OnbirthdayNVChanging(value);
					this.SendPropertyChanging();
					this._birthdayNV = value;
					this.SendPropertyChanged("birthdayNV");
					this.OnbirthdayNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hiredayNV", DbType="Date NOT NULL")]
		public System.DateTime hiredayNV
		{
			get
			{
				return this._hiredayNV;
			}
			set
			{
				if ((this._hiredayNV != value))
				{
					this.OnhiredayNVChanging(value);
					this.SendPropertyChanging();
					this._hiredayNV = value;
					this.SendPropertyChanged("hiredayNV");
					this.OnhiredayNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_addressNV", DbType="NChar(50) NOT NULL", CanBeNull=false)]
		public string addressNV
		{
			get
			{
				return this._addressNV;
			}
			set
			{
				if ((this._addressNV != value))
				{
					this.OnaddressNVChanging(value);
					this.SendPropertyChanging();
					this._addressNV = value;
					this.SendPropertyChanged("addressNV");
					this.OnaddressNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_salaryNV", DbType="Decimal(18,0) NOT NULL")]
		public decimal salaryNV
		{
			get
			{
				return this._salaryNV;
			}
			set
			{
				if ((this._salaryNV != value))
				{
					this.OnsalaryNVChanging(value);
					this.SendPropertyChanging();
					this._salaryNV = value;
					this.SendPropertyChanged("salaryNV");
					this.OnsalaryNVChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.dataKH")]
	public partial class dataKH : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _idKH;
		
		private string _nameKH;
		
		private string _phoneKH;
		
		private string _addressKH;
		
		private string _genderKH;
		
		private System.DateTime _birthdayKH;
		
		private System.DateTime _timeInKH;
		
		private System.DateTime _timeOutKH;
		
		private string _brandKH;
		
		private string _typeKH;
		
		private string _colorKH;
		
		private string _numberPlateKH;
		
		private System.Data.Linq.Binary _imageKH;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidKHChanging(string value);
    partial void OnidKHChanged();
    partial void OnnameKHChanging(string value);
    partial void OnnameKHChanged();
    partial void OnphoneKHChanging(string value);
    partial void OnphoneKHChanged();
    partial void OnaddressKHChanging(string value);
    partial void OnaddressKHChanged();
    partial void OngenderKHChanging(string value);
    partial void OngenderKHChanged();
    partial void OnbirthdayKHChanging(System.DateTime value);
    partial void OnbirthdayKHChanged();
    partial void OntimeInKHChanging(System.DateTime value);
    partial void OntimeInKHChanged();
    partial void OntimeOutKHChanging(System.DateTime value);
    partial void OntimeOutKHChanged();
    partial void OnbrandKHChanging(string value);
    partial void OnbrandKHChanged();
    partial void OntypeKHChanging(string value);
    partial void OntypeKHChanged();
    partial void OncolorKHChanging(string value);
    partial void OncolorKHChanged();
    partial void OnnumberPlateKHChanging(string value);
    partial void OnnumberPlateKHChanged();
    partial void OnimageKHChanging(System.Data.Linq.Binary value);
    partial void OnimageKHChanged();
    #endregion
		
		public dataKH()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idKH", DbType="NChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string idKH
		{
			get
			{
				return this._idKH;
			}
			set
			{
				if ((this._idKH != value))
				{
					this.OnidKHChanging(value);
					this.SendPropertyChanging();
					this._idKH = value;
					this.SendPropertyChanged("idKH");
					this.OnidKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nameKH", DbType="NChar(50) NOT NULL", CanBeNull=false)]
		public string nameKH
		{
			get
			{
				return this._nameKH;
			}
			set
			{
				if ((this._nameKH != value))
				{
					this.OnnameKHChanging(value);
					this.SendPropertyChanging();
					this._nameKH = value;
					this.SendPropertyChanged("nameKH");
					this.OnnameKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phoneKH", DbType="NChar(50) NOT NULL", CanBeNull=false)]
		public string phoneKH
		{
			get
			{
				return this._phoneKH;
			}
			set
			{
				if ((this._phoneKH != value))
				{
					this.OnphoneKHChanging(value);
					this.SendPropertyChanging();
					this._phoneKH = value;
					this.SendPropertyChanged("phoneKH");
					this.OnphoneKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_addressKH", DbType="NChar(50) NOT NULL", CanBeNull=false)]
		public string addressKH
		{
			get
			{
				return this._addressKH;
			}
			set
			{
				if ((this._addressKH != value))
				{
					this.OnaddressKHChanging(value);
					this.SendPropertyChanging();
					this._addressKH = value;
					this.SendPropertyChanged("addressKH");
					this.OnaddressKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_genderKH", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string genderKH
		{
			get
			{
				return this._genderKH;
			}
			set
			{
				if ((this._genderKH != value))
				{
					this.OngenderKHChanging(value);
					this.SendPropertyChanging();
					this._genderKH = value;
					this.SendPropertyChanged("genderKH");
					this.OngenderKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_birthdayKH", DbType="Date NOT NULL")]
		public System.DateTime birthdayKH
		{
			get
			{
				return this._birthdayKH;
			}
			set
			{
				if ((this._birthdayKH != value))
				{
					this.OnbirthdayKHChanging(value);
					this.SendPropertyChanging();
					this._birthdayKH = value;
					this.SendPropertyChanged("birthdayKH");
					this.OnbirthdayKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_timeInKH", DbType="DateTime NOT NULL")]
		public System.DateTime timeInKH
		{
			get
			{
				return this._timeInKH;
			}
			set
			{
				if ((this._timeInKH != value))
				{
					this.OntimeInKHChanging(value);
					this.SendPropertyChanging();
					this._timeInKH = value;
					this.SendPropertyChanged("timeInKH");
					this.OntimeInKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_timeOutKH", DbType="DateTime NOT NULL")]
		public System.DateTime timeOutKH
		{
			get
			{
				return this._timeOutKH;
			}
			set
			{
				if ((this._timeOutKH != value))
				{
					this.OntimeOutKHChanging(value);
					this.SendPropertyChanging();
					this._timeOutKH = value;
					this.SendPropertyChanged("timeOutKH");
					this.OntimeOutKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_brandKH", DbType="NChar(50) NOT NULL", CanBeNull=false)]
		public string brandKH
		{
			get
			{
				return this._brandKH;
			}
			set
			{
				if ((this._brandKH != value))
				{
					this.OnbrandKHChanging(value);
					this.SendPropertyChanging();
					this._brandKH = value;
					this.SendPropertyChanged("brandKH");
					this.OnbrandKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_typeKH", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string typeKH
		{
			get
			{
				return this._typeKH;
			}
			set
			{
				if ((this._typeKH != value))
				{
					this.OntypeKHChanging(value);
					this.SendPropertyChanging();
					this._typeKH = value;
					this.SendPropertyChanged("typeKH");
					this.OntypeKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_colorKH", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string colorKH
		{
			get
			{
				return this._colorKH;
			}
			set
			{
				if ((this._colorKH != value))
				{
					this.OncolorKHChanging(value);
					this.SendPropertyChanging();
					this._colorKH = value;
					this.SendPropertyChanged("colorKH");
					this.OncolorKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numberPlateKH", DbType="NChar(50) NOT NULL", CanBeNull=false)]
		public string numberPlateKH
		{
			get
			{
				return this._numberPlateKH;
			}
			set
			{
				if ((this._numberPlateKH != value))
				{
					this.OnnumberPlateKHChanging(value);
					this.SendPropertyChanging();
					this._numberPlateKH = value;
					this.SendPropertyChanged("numberPlateKH");
					this.OnnumberPlateKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_imageKH", DbType="VarBinary(MAX) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary imageKH
		{
			get
			{
				return this._imageKH;
			}
			set
			{
				if ((this._imageKH != value))
				{
					this.OnimageKHChanging(value);
					this.SendPropertyChanging();
					this._imageKH = value;
					this.SendPropertyChanged("imageKH");
					this.OnimageKHChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CarSpaceData")]
	public partial class CarSpaceData : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _location;
		
		private string _idCustomer;
		
		private string _numberPlate;
		
		private string _brand;
		
		private System.Data.Linq.Binary _image;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnlocationChanging(string value);
    partial void OnlocationChanged();
    partial void OnidCustomerChanging(string value);
    partial void OnidCustomerChanged();
    partial void OnnumberPlateChanging(string value);
    partial void OnnumberPlateChanged();
    partial void OnbrandChanging(string value);
    partial void OnbrandChanged();
    partial void OnimageChanging(System.Data.Linq.Binary value);
    partial void OnimageChanged();
    #endregion
		
		public CarSpaceData()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_location", DbType="NChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string location
		{
			get
			{
				return this._location;
			}
			set
			{
				if ((this._location != value))
				{
					this.OnlocationChanging(value);
					this.SendPropertyChanging();
					this._location = value;
					this.SendPropertyChanged("location");
					this.OnlocationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idCustomer", DbType="NChar(30) NOT NULL", CanBeNull=false)]
		public string idCustomer
		{
			get
			{
				return this._idCustomer;
			}
			set
			{
				if ((this._idCustomer != value))
				{
					this.OnidCustomerChanging(value);
					this.SendPropertyChanging();
					this._idCustomer = value;
					this.SendPropertyChanged("idCustomer");
					this.OnidCustomerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numberPlate", DbType="NChar(30) NOT NULL", CanBeNull=false)]
		public string numberPlate
		{
			get
			{
				return this._numberPlate;
			}
			set
			{
				if ((this._numberPlate != value))
				{
					this.OnnumberPlateChanging(value);
					this.SendPropertyChanging();
					this._numberPlate = value;
					this.SendPropertyChanged("numberPlate");
					this.OnnumberPlateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_brand", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string brand
		{
			get
			{
				return this._brand;
			}
			set
			{
				if ((this._brand != value))
				{
					this.OnbrandChanging(value);
					this.SendPropertyChanging();
					this._brand = value;
					this.SendPropertyChanged("brand");
					this.OnbrandChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_image", DbType="VarBinary(MAX) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary image
		{
			get
			{
				return this._image;
			}
			set
			{
				if ((this._image != value))
				{
					this.OnimageChanging(value);
					this.SendPropertyChanging();
					this._image = value;
					this.SendPropertyChanged("image");
					this.OnimageChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.dulieuMotoSpace")]
	public partial class dulieuMotoSpace : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _location;
		
		private string _idCustomer;
		
		private string _numberPlate;
		
		private string _brand;
		
		private System.Data.Linq.Binary _image;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnlocationChanging(string value);
    partial void OnlocationChanged();
    partial void OnidCustomerChanging(string value);
    partial void OnidCustomerChanged();
    partial void OnnumberPlateChanging(string value);
    partial void OnnumberPlateChanged();
    partial void OnbrandChanging(string value);
    partial void OnbrandChanged();
    partial void OnimageChanging(System.Data.Linq.Binary value);
    partial void OnimageChanged();
    #endregion
		
		public dulieuMotoSpace()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_location", DbType="NChar(30) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string location
		{
			get
			{
				return this._location;
			}
			set
			{
				if ((this._location != value))
				{
					this.OnlocationChanging(value);
					this.SendPropertyChanging();
					this._location = value;
					this.SendPropertyChanged("location");
					this.OnlocationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idCustomer", DbType="NChar(30) NOT NULL", CanBeNull=false)]
		public string idCustomer
		{
			get
			{
				return this._idCustomer;
			}
			set
			{
				if ((this._idCustomer != value))
				{
					this.OnidCustomerChanging(value);
					this.SendPropertyChanging();
					this._idCustomer = value;
					this.SendPropertyChanged("idCustomer");
					this.OnidCustomerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numberPlate", DbType="NChar(30) NOT NULL", CanBeNull=false)]
		public string numberPlate
		{
			get
			{
				return this._numberPlate;
			}
			set
			{
				if ((this._numberPlate != value))
				{
					this.OnnumberPlateChanging(value);
					this.SendPropertyChanging();
					this._numberPlate = value;
					this.SendPropertyChanged("numberPlate");
					this.OnnumberPlateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_brand", DbType="NChar(30) NOT NULL", CanBeNull=false)]
		public string brand
		{
			get
			{
				return this._brand;
			}
			set
			{
				if ((this._brand != value))
				{
					this.OnbrandChanging(value);
					this.SendPropertyChanging();
					this._brand = value;
					this.SendPropertyChanged("brand");
					this.OnbrandChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_image", DbType="VarBinary(MAX) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary image
		{
			get
			{
				return this._image;
			}
			set
			{
				if ((this._image != value))
				{
					this.OnimageChanging(value);
					this.SendPropertyChanging();
					this._image = value;
					this.SendPropertyChanged("image");
					this.OnimageChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.feedbackData")]
	public partial class feedbackData : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _FeedBack;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnFeedBackChanging(string value);
    partial void OnFeedBackChanged();
    #endregion
		
		public feedbackData()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FeedBack", DbType="NChar(100) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string FeedBack
		{
			get
			{
				return this._FeedBack;
			}
			set
			{
				if ((this._FeedBack != value))
				{
					this.OnFeedBackChanging(value);
					this.SendPropertyChanging();
					this._FeedBack = value;
					this.SendPropertyChanged("FeedBack");
					this.OnFeedBackChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.dataHistory")]
	public partial class dataHistory : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _idKH;
		
		private string _nameKH;
		
		private string _typeKH;
		
		private string _numberPlate;
		
		private System.DateTime _timeInKH;
		
		private System.DateTime _timeOutKH;
		
		private decimal _priceKH;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidKHChanging(string value);
    partial void OnidKHChanged();
    partial void OnnameKHChanging(string value);
    partial void OnnameKHChanged();
    partial void OntypeKHChanging(string value);
    partial void OntypeKHChanged();
    partial void OnnumberPlateChanging(string value);
    partial void OnnumberPlateChanged();
    partial void OntimeInKHChanging(System.DateTime value);
    partial void OntimeInKHChanged();
    partial void OntimeOutKHChanging(System.DateTime value);
    partial void OntimeOutKHChanged();
    partial void OnpriceKHChanging(decimal value);
    partial void OnpriceKHChanged();
    #endregion
		
		public dataHistory()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idKH", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string idKH
		{
			get
			{
				return this._idKH;
			}
			set
			{
				if ((this._idKH != value))
				{
					this.OnidKHChanging(value);
					this.SendPropertyChanging();
					this._idKH = value;
					this.SendPropertyChanged("idKH");
					this.OnidKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nameKH", DbType="NChar(50) NOT NULL", CanBeNull=false)]
		public string nameKH
		{
			get
			{
				return this._nameKH;
			}
			set
			{
				if ((this._nameKH != value))
				{
					this.OnnameKHChanging(value);
					this.SendPropertyChanging();
					this._nameKH = value;
					this.SendPropertyChanged("nameKH");
					this.OnnameKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_typeKH", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string typeKH
		{
			get
			{
				return this._typeKH;
			}
			set
			{
				if ((this._typeKH != value))
				{
					this.OntypeKHChanging(value);
					this.SendPropertyChanging();
					this._typeKH = value;
					this.SendPropertyChanged("typeKH");
					this.OntypeKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numberPlate", DbType="NChar(30) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string numberPlate
		{
			get
			{
				return this._numberPlate;
			}
			set
			{
				if ((this._numberPlate != value))
				{
					this.OnnumberPlateChanging(value);
					this.SendPropertyChanging();
					this._numberPlate = value;
					this.SendPropertyChanged("numberPlate");
					this.OnnumberPlateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_timeInKH", DbType="DateTime NOT NULL")]
		public System.DateTime timeInKH
		{
			get
			{
				return this._timeInKH;
			}
			set
			{
				if ((this._timeInKH != value))
				{
					this.OntimeInKHChanging(value);
					this.SendPropertyChanging();
					this._timeInKH = value;
					this.SendPropertyChanged("timeInKH");
					this.OntimeInKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_timeOutKH", DbType="DateTime NOT NULL")]
		public System.DateTime timeOutKH
		{
			get
			{
				return this._timeOutKH;
			}
			set
			{
				if ((this._timeOutKH != value))
				{
					this.OntimeOutKHChanging(value);
					this.SendPropertyChanging();
					this._timeOutKH = value;
					this.SendPropertyChanged("timeOutKH");
					this.OntimeOutKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_priceKH", DbType="Decimal(18,0) NOT NULL")]
		public decimal priceKH
		{
			get
			{
				return this._priceKH;
			}
			set
			{
				if ((this._priceKH != value))
				{
					this.OnpriceKHChanging(value);
					this.SendPropertyChanging();
					this._priceKH = value;
					this.SendPropertyChanged("priceKH");
					this.OnpriceKHChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.dataHisKH")]
	public partial class dataHisKH : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _idKH;
		
		private string _nameKH;
		
		private string _typeKH;
		
		private string _numberPlate;
		
		private System.DateTime _timeIn;
		
		private System.DateTime _timeOut;
		
		private decimal _priceKH;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidKHChanging(string value);
    partial void OnidKHChanged();
    partial void OnnameKHChanging(string value);
    partial void OnnameKHChanged();
    partial void OntypeKHChanging(string value);
    partial void OntypeKHChanged();
    partial void OnnumberPlateChanging(string value);
    partial void OnnumberPlateChanged();
    partial void OntimeInChanging(System.DateTime value);
    partial void OntimeInChanged();
    partial void OntimeOutChanging(System.DateTime value);
    partial void OntimeOutChanged();
    partial void OnpriceKHChanging(decimal value);
    partial void OnpriceKHChanged();
    #endregion
		
		public dataHisKH()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idKH", DbType="NChar(30) NOT NULL", CanBeNull=false)]
		public string idKH
		{
			get
			{
				return this._idKH;
			}
			set
			{
				if ((this._idKH != value))
				{
					this.OnidKHChanging(value);
					this.SendPropertyChanging();
					this._idKH = value;
					this.SendPropertyChanged("idKH");
					this.OnidKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nameKH", DbType="NChar(30) NOT NULL", CanBeNull=false)]
		public string nameKH
		{
			get
			{
				return this._nameKH;
			}
			set
			{
				if ((this._nameKH != value))
				{
					this.OnnameKHChanging(value);
					this.SendPropertyChanging();
					this._nameKH = value;
					this.SendPropertyChanged("nameKH");
					this.OnnameKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_typeKH", DbType="NChar(30) NOT NULL", CanBeNull=false)]
		public string typeKH
		{
			get
			{
				return this._typeKH;
			}
			set
			{
				if ((this._typeKH != value))
				{
					this.OntypeKHChanging(value);
					this.SendPropertyChanging();
					this._typeKH = value;
					this.SendPropertyChanged("typeKH");
					this.OntypeKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numberPlate", DbType="NChar(30) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string numberPlate
		{
			get
			{
				return this._numberPlate;
			}
			set
			{
				if ((this._numberPlate != value))
				{
					this.OnnumberPlateChanging(value);
					this.SendPropertyChanging();
					this._numberPlate = value;
					this.SendPropertyChanged("numberPlate");
					this.OnnumberPlateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_timeIn", DbType="DateTime NOT NULL")]
		public System.DateTime timeIn
		{
			get
			{
				return this._timeIn;
			}
			set
			{
				if ((this._timeIn != value))
				{
					this.OntimeInChanging(value);
					this.SendPropertyChanging();
					this._timeIn = value;
					this.SendPropertyChanged("timeIn");
					this.OntimeInChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_timeOut", DbType="DateTime NOT NULL")]
		public System.DateTime timeOut
		{
			get
			{
				return this._timeOut;
			}
			set
			{
				if ((this._timeOut != value))
				{
					this.OntimeOutChanging(value);
					this.SendPropertyChanging();
					this._timeOut = value;
					this.SendPropertyChanged("timeOut");
					this.OntimeOutChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_priceKH", DbType="Decimal(18,4) NOT NULL")]
		public decimal priceKH
		{
			get
			{
				return this._priceKH;
			}
			set
			{
				if ((this._priceKH != value))
				{
					this.OnpriceKHChanging(value);
					this.SendPropertyChanging();
					this._priceKH = value;
					this.SendPropertyChanged("priceKH");
					this.OnpriceKHChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
